### PR TITLE
Bump Postgres to 16

### LINKED ISSUE #218: Postgres 15
Postgres 15 was [released in October 2022](https://www.postgresql.org/about/news/postgresql-15-released-2526/). The template [currently uses Postgres 14](https://github.com/navapbc/template-application-flask/blob/0dd8c92777da778ad0a02ace910e3210b6b58bab/docker-compose.yml#L6).

### PR DESCRIPTION
**Pull request by KevinJBoyer**
## Ticket

Resolves #218 

## Changes

Change Docker image used for local development to Postgres 16.

## Context for reviewers
Sibling PR for [bump to 16.2 in the infra template](https://github.com/navapbc/template-infra/pull/627).

## Testing
All existing tests pass.

### CODE REVIEW

**Comment by KevinJBoyer** [comment]
@chouinar to coordinate with the change in the infra template, I went ahead and requested your review on this -- I'll plan to merge this if/when the corresponding infra template PR is merged.

**Review by chouinar — APPROVED** [review]
LGTM!

Skimming through the changelog for Postgres 16, I don't see anything that should impact anything locally, but there are a ton of changes.

https://www.postgresql.org/docs/release/16.0/

**Comment by lorenyu** [comment]
[aws docs](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_UpgradeDBInstance.PostgreSQL.html#USER_UpgradeDBInstance.PostgreSQL.MajorVersion.Process) seem to indicate that we can only go up to 15.6 from 14.6 

so we might need to do this in two steps/PRs
image

**Comment by chouinar** [comment]
> [aws docs](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_UpgradeDBInstance.PostgreSQL.html#USER_UpgradeDBInstance.PostgreSQL.MajorVersion.Process) seem to indicate that we can only go up to 15.6 from 14.6
> 
> so we might need to do this in two steps/PRs image

Wouldn't be an issue with the docker-compose file since that only affects your local instance of the DB. If you want to be very careful, you could upgrade this to v15 when the infra gets changed, and then upgrade it again to v16

**Comment by lorenyu** [comment]
sorry i thought this was the infra template PR ignore my previous comment

**Pull request merged**
